Add GitHub.com themes
primer/github-vscode-theme pull request #132
Opened 2021-02-02 13:40 UTC by simurai

This adds the `GitHub.com Light` + `GitHub.com Dark` themes. It's the same as #102 (that got reverted), but still keeps the old themes.

- `GitHub.com Light` ✨  new ✨ 
- `GitHub.com Dark` ✨  new ✨ 
- `GitHub Light` stays as is
- `GitHub Dark` stays as is

GitHub.com Light | GitHub.com Dark
--- | ---
![light](https://user-images.githubusercontent.com/378023/102190514-7b395380-3efb-11eb-8f28-cc25e29a48f4.png) | ![dark](https://user-images.githubusercontent.com/378023/102190528-7f657100-3efb-11eb-9d55-b34ec8cef9c4.png)

**Note**: Currently `GitHub Light` and `GitHub.com Light` are almost the same. A bit different contrast for text. It almost feels redundant having both. But who knows, that could change in the future. 🤷

2021-02-02 18:38 UTC, dominicegginton approved these changes

2021-02-05 12:38 UTC, Gameghostify commented
@simurai Thank you for this PR, this feels like a really good solution

2021-02-05 12:41 UTC, samuelramox approved these changes

2021-02-05 15:00 UTC, mishushakov approved these changes

2021-02-06 16:30 UTC, davi-mbatista commented
Awesome. Can't wait to have it merged!

2021-02-09 15:29 UTC, bogdansoare commented
Anything stopping this PR from being merged?

2021-02-10 00:01 UTC, simurai commented
> Anything stopping this PR from being merged?

I think we still have to decide if `GitHub.com Dark` is the right name moving forward. /cc @broccolini 

---

If you already wanna try the github.com theme, you can go back to a previous version by clicking on the dropdown next to "Uninstall":

![Screen Shot 2021-02-10 at 8 55 03](https://user-images.githubusercontent.com/378023/107444651-502b5300-6b7e-11eb-8630-d2809143091b.png)

Then choose "Install Another Version..." and pick `2.0.1`:

![Screen Shot 2021-02-10 at 9 00 16](https://user-images.githubusercontent.com/378023/107444735-751fc600-6b7e-11eb-90bf-f6126355afd9.png)

2021-02-16 18:22 UTC, duong-le commented
How about this?
- GitHub.com Light, GitHub Light -> GitHub Light (Since they are almost the same)
- GitHub Dark -> GitHub Dark Classic
- GitHub.com Dark -> GitHub Dark

2021-02-23 12:07 UTC, dominicegginton requested changes

2021-02-23 12:07 UTC, dominicegginton commented on src/dotcom/theme.js
> +      "terminal.foreground": color.text.secondary,
Once merged the [color-modes](https://github.com/primer/primitives/tree/mkt/color-modes) branch in the [primer/primitives](https://github.com/primer/primitives) module will provide ansi colors for the terminal, we should add these to this theme
``` js
'terminal.ansiBlack': color.ansi.black,
'terminal.ansiRed': color.ansi.red,
'terminal.ansiGreen': color.ansi.green,
'terminal.ansiYellow': color.ansi.yellow,
'terminal.ansiBlue': color.ansi.blue,
'terminal.ansiMagenta': color.ansi.magenta,
'terminal.ansiCyan': color.ansi.cyan,
'terminal.ansiWhite': color.ansi.white,
'terminal.ansiBrightBlack': color.ansi.blackBright,
'terminal.ansiBrightRed': color.ansi.redBright,
'terminal.ansiBrightGreen': color.ansi.greenBright,
'terminal.ansiBrightYellow': color.ansi.yellowBright,
'terminal.ansiBrightBlue': color.ansi.blackBright,
'terminal.ansiBrightMagenta': color.ansi.magentaBright,
'terminal.ansiBrightCyan': color.ansi.cyanBright,
'terminal.ansiBrightWhite': color.ansi.whiteBright,
```

2021-03-10 16:52 UTC, dominicegginton commented
@simurai, just noticed that GitHub will be adding, a [dimmed](https://github.com/github/roadmap/issues/175) and [deuteranomaly colorblind](https://github.com/github/roadmap/issues/176) theme to GitHub.com. We should add these to the vscode theme extension to keep consistent. This could clear up some of the confusion that was caused when dark mode was released for this extension. Let me know if you need any help on this 😄

2021-03-17 13:33 UTC, dominicegginton commented
### Suggestion
With the addition of the new GitHub.com dimmed theme recently merged into this PR (#138), I believe we can simplify theme names and remove the original themes reducing confusion and simplifying user experience. My suggestion is:

**Remove**
- `GitHub Light`: Due to high similarity to **GitHub.com Light**
- `GitHub Dark`: Due to high similarity to **GitHub.com Dimmed**

As you can see it is clear that the new old themes are extremely similar to the new `.com` themes. These old themes have been forked as discussed in #114 and the new dimmed theme addresses the main concern of contrast that resulted in the rollback of the new dark theme in the first place. Due to this, I believe it is not worth supporting the old thems Moving forward. 
|GitHub Light|GitHub.com Light|
|----------------|------------------------|
|![screenshot-Wed-17Mar21_13 15](https://user-images.githubusercontent.com/28626241/111473382-e412b080-8722-11eb-81f7-f386146f61e7.png)|![screenshot-Wed-17Mar21_13 15_000](https://user-images.githubusercontent.com/28626241/111473499-0278ac00-8723-11eb-8f26-78d8fad17c6a.png)|

|GitHub Dark|GitHub.com Dimmed|
|----------------|----------------------------|
|![screenshot-Wed-17Mar21_13 17](https://user-images.githubusercontent.com/28626241/111473741-44095700-8723-11eb-8d3c-c66e78f0b762.png)|![screenshot-Wed-17Mar21_13 18](https://user-images.githubusercontent.com/28626241/111473765-48357480-8723-11eb-8016-e8470a38c79f.png)|




**Rename**
- `GitHub.com Light`  :arrow_right:  `GitHub Light`
- `GitHub.com Dark`  :arrow_right:  `GitHub Dark`
- `GitHub.com Dark Dimmed`  :arrow_right:  `GitHub Dimmed`

If removing the original themes it makes sense to rename these removing the `.com`.

**Result**

This would leave us with these three themes that follow the new GitHub.com website:

|GitHub Light|GitHub Dark|GitHub Dimmed|
|-----------------|----------------|---------------------|
|![screenshot-Wed-17Mar21_13 15_000](https://user-images.githubusercontent.com/28626241/111473499-0278ac00-8723-11eb-8f26-78d8fad17c6a.png)|![screenshot-Wed-17Mar21_13 28](https://user-images.githubusercontent.com/28626241/111475163-b890c580-8724-11eb-9c11-b79d81ff4347.png)|![screenshot-Wed-17Mar21_13 18](https://user-images.githubusercontent.com/28626241/111473765-48357480-8723-11eb-8016-e8470a38c79f.png)|

If anyone has any comments or feedback for this suggestion I'm making please let me know. If this is something people and @simurai want I'm happy to open a PR for review.

2021-04-02 08:25 UTC, simurai commented
**Update**: With https://github.com/primer/github-vscode-theme/pull/132/commits/ea0286529cb18141461f3e0a4feb65386b8a4c7e, the naming of the themes are:

- `GitHub Light` stays as is
- `GitHub Dark` stays as is
- `GitHub Light Default` ✨  new ✨ 
- `GitHub Dark Default` ✨  new ✨ 
- `GitHub Dark Dimmed` ✨  new ✨ 

I'm not a big fan of the word "Default" in the name, but it allows the old `Light/Dark` themes to stay and it matches how [github.com calls the themes](https://github.com/settings/appearance) (with switched order):

![image](https://user-images.githubusercontent.com/378023/113397545-2e10bd00-93d8-11eb-847b-3b3c9afcde5e.png)

2021-04-02 11:41 UTC, nonameolsson approved these changes

2021-04-02 21:58 UTC, joshmanders commented
@simurai with these changes can we see an update to the extension soon? I'd really like to turn auto updating for extensions back on. Every time update happens it updates this extension and I have to roll it back, so had to turn auto update off.

2021-04-05 10:56 UTC, stagefright5 commented
I didn't want to be "that" guy, but, come on, this PR has been open for more than 2 months, which is honestly quite ridiculous.
If naming is the concern, that can be decided and changed even after this gets released. Please merge this PR.
Thanks

2021-04-05 13:16 UTC, dominicegginton commented
@stagefright5 I know a lot of people (including me) are excited about the new official themes that will be added with this PR. But I'm sure the GitHub primer team are busy and want to make sure they have a clear and consistent direction to their design system. Remember this is also the default theme for GitHub Codespaces so is important to the GitHub brand image that it's of high standard.

2021-04-06 07:12 UTC, simurai commented
> If naming is the concern, that can be decided and changed even after this gets released.

[We tried to rename it before](https://github.com/primer/github-vscode-theme/discussions/114), but I think VS Code uses the name as the identifier, so we can't really change names later without causing disruptions.

> Remember this is also the default theme for GitHub Codespaces

Yep, this is not really a "stand-alone" theme and is part of GitHub's release cycles. So sometimes things can get postponed.

2021-04-06 14:01 UTC, joshmanders commented
Regardless of how long it takes to release, thank you @simurai and everyone for your work. I've been a long time Dracula theme user, since Reno released it, everywhere a theme for it exists I used it... GitHub's new dark theme is the first time I ever saw a theme that made me want to switch.

2021-04-09 07:15 UTC, nero120 commented
This looks awesome guys, great work! Looks like the PR is awaiting "final approval" - just wondering who needs to do that as I'm mega impatient to use dark dimmed! Looks like all the dev work has been done right?

2021-04-14 10:14 UTC, nonameolsson approved these changes

2021-04-14 13:54 UTC, simurai commented
> nonameolsson approved these changes

Ok, in that case, let's merge it. 🚢

2021-04-14 13:54 UTC, merged